# XNMT supports various ways to preprocess data as demonstrated in this example.
# Note that some preprocessing functionality relies on third-party tools.
!Experiment
  name: new_model_preprocessed_be_epoch30_multilingual
  exp_global: !ExpGlobal
    # define some named strings that can be used throughout the experiment config:
    placeholders:
      DATA_IN: src/preprocess/preprocessed_data/merged_files/be_ru_hun
      DATA_EV: src/preprocess/preprocessed_data/en_be
      DATA_OUT: output/en_be
      SRC_LAN: be
      TRG_LAN: en
  model: !DefaultTranslator
    src_reader: !PlainTextReader
      vocab: !Vocab
        vocab_file: '{DATA_IN}/src_vocab.txt'
    trg_reader: !PlainTextReader
      vocab: !Vocab
        vocab_file: '{DATA_IN}/trg_vocab.txt'
    src_embedder: !SimpleWordEmbedder
      emb_dim: 300
    encoder: !BiLSTMSeqTransducer
      layers: 1
    attender: !MlpAttender
      hidden_dim: 128
      state_dim: 128
      input_dim: 128
    decoder: !AutoRegressiveDecoder
      embedder: !SimpleWordEmbedder
        emb_dim: 128
      rnn: !UniLSTMSeqTransducer
        layers: 1
      transform: !AuxNonLinear
        output_dim: 300
      bridge: !NoBridge {}
    inference: !AutoRegressiveInference
      post_process: join-bpe
  train: !SimpleTrainingRegimen
    trainer: !AdamTrainer
      alpha: 0.0002
    batcher: !WordSrcBatcher
      avg_batch_size: 32
    lr_decay: 0.5
    run_for_epochs: 30
    patience: 500
    initial_patience: 500
    src_file: '{DATA_IN}/merged_src_train.txt'
    trg_file: '{DATA_IN}/merged_tar_train.txt'
    dev_tasks:
      - !AccuracyEvalTask
        eval_metrics: bleu
        src_file: '{DATA_IN}/merged_src_dev.txt'
        ref_file: '{DATA_IN}/merged_tar_dev.txt'
        hyp_file: '{DATA_OUT}/{EXP}.dev_hyp.txt'
      - !LossEvalTask
        src_file: '{DATA_IN}/merged_src_dev.txt'
        ref_file: '{DATA_IN}/merged_tar_dev.txt'
  evaluate:
  - !AccuracyEvalTask
    eval_metrics: bleu
    src_file: '{DATA_EV}/test.tok.norm.{SRC_LAN}'
    ref_file: '{DATA_EV}/test.norm.{TRG_LAN}'
    hyp_file: '{DATA_OUT}/{EXP}.test_hyp'